version: 2

models:
  - name: stg_employees
    columns:
      - name: employee_id
        tests:
          - not_null
          - unique

  - name: stg_departments
    columns:
      - name: department_id
        tests:
          - not_null
          - unique

  - name: stg_locations
    columns:
      - name: location_id
        tests:
          - not_null
          - unique

  - name: stg_jobs
    columns:
      - name: job_id
        tests:
          - not_null
          - unique

  - name: stg_countries
    columns:
      - name: country_id
        tests:
          - not_null
          - unique

  - name: stg_regions
    columns:
      - name: region_id
        tests:
          - not_null
          - unique

  - name: stg_salary
    columns:
      - name: employee_id
        tests:
          - not_null
          - unique

  - name: dim_employees
    columns:
      - name: employee_id
        tests:
          - not_null
          - unique
          
  - name: dim_departments
    columns:
      - name: department_id
        tests:
          - not_null
          - unique

  - name: dim_loactions
    columns:
      - name: location_id
        tests:
          - not_null
          - unique
      
  - name: dim_jobs
    columns:
      - name: job_id
        tests:
          - not_null
          - unique

  - name: dim_countries
    columns:
      - name: country_id
        tests:
          - not_null
          - unique

  - name: dim_regions
    columns:
      - name: region_id
        tests:
          - not_null
          - unique

  - name: fct_salary
    columns:
      - name: employee_id
        tests:
          - not_null
          - unique
  

